{% set version = "0.9.8" %}

package:
  name: libcmaes
  version: {{ version }}

source:
  fn: libcmaes-{{ version }}.tar.gz
  url: https://github.com/beniz/libcmaes/archive/{{ version }}.tar.gz
  sha256: 421367fa8c09e7446b383f57b6fb5e839ee74f4343b87c34f6a9e4942aa1ea66

build:
  number: 0

requirements:
  build:
    - libtool  # [unix]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cmake >=3.12.1
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost
    - eigen
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - boost

test:
  commands:
    - test -f ${PREFIX}/include/libcmaes/cmaes.h  # [unix]
    - test -f ${PREFIX}/lib/libcmaes${SHLIB_EXT}  # [unix]
  imports:
    - lcmaes

about:
  home: https://github.com/beniz/libcmaes
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: High performance blackbox stochastic optimization using the CMA-ES algorithm

extra:
  recipe-maintainers:
    - jschueller
