{% set version = "0.9.5" %}

package:
  name: libcmaes
  version: {{ version }}

source:
  url: https://github.com/beniz/libcmaes/archive/{{ version }}.tar.gz
  sha256: 899fcc44b551e4976a77e48e41bdd5dafc3394bd3fcb3c55996c02e4267bfa28
  patches:
    # https://github.com/beniz/libcmaes/pull/149
    - py3k.patch

build:
  number: 3
  skip: true  # [win and vc<14]

requirements:
  build:
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost
    - eigen
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - boost

test:
  commands:
    - test -f ${PREFIX}/include/libcmaes/cmaes.h  # [unix]
    - test -f ${PREFIX}/lib/libcmaes${SHLIB_EXT}  # [unix]
  imports:
    - lcmaes

about:
  home: https://github.com/beniz/libcmaes
  license: LGPL-3.0
  license_file: COPYING
  summary: High performance blackbox stochastic optimization using the CMA-ES algorithm

extra:
  recipe-maintainers:
    - jschueller
