{% set version = "0.9.5" %}

package:
  name: libcmaes
  version: {{ version }}

source:
  fn: libcmaes-{{ version }}.tar.gz
  url: https://github.com/beniz/libcmaes/archive/{{ version }}.tar.gz
  sha256: 899fcc44b551e4976a77e48e41bdd5dafc3394bd3fcb3c55996c02e4267bfa28
  patches:
    # https://github.com/beniz/libcmaes/pull/149
    - py3k.patch

build:
  number: 2
  # does not build with vc9
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - cmake  # [win]
    - python
    - boost 1.64.*
    - eigen
    - numpy x.x
  run:
    - python
    - numpy x.x
    - boost 1.64.*

test:
  commands:
    - test -f ${PREFIX}/include/libcmaes/cmaes.h  # [unix]
    - test -f ${PREFIX}/lib/libcmaes.so  # [linux]
    - test -f ${PREFIX}/lib/libcmaes.dylib  # [osx]
  imports:
    - lcmaes

about:
  home: https://github.com/beniz/libcmaes
  license: LGPL3
  license_file: COPYING
  summary: High performance blackbox stochastic optimization using the CMA-ES algorithm

extra:
  recipe-maintainers:
    - jschueller
