{% set version = "0.10" %}

package:
  name: libcmaes
  version: {{ version }}

source:
  fn: libcmaes-{{ version }}.tar.gz
  url: https://github.com/beniz/libcmaes/archive/v{{ version }}.tar.gz
  sha256: a77fb892654356c5657dd677161b7c67b196dc732cfb77eaca6708abc4f6cffc

build:
  number: 0

requirements:
  build:
    - libtool  # [unix]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - libboost-python-devel
    - eigen
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - test -f ${PREFIX}/include/libcmaes/cmaes.h  # [unix]
    - test -f ${PREFIX}/lib/libcmaes${SHLIB_EXT}  # [unix]
  imports:
    - lcmaes

about:
  home: https://github.com/beniz/libcmaes
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: High performance blackbox stochastic optimization using the CMA-ES algorithm

extra:
  recipe-maintainers:
    - jschueller
