{% set version = "0.9.6.1" %}

package:
  name: libcmaes
  version: {{ version }}

source:
  fn: libcmaes-{{ version }}.tar.gz
  url: https://github.com/beniz/libcmaes/archive/{{ version }}.tar.gz
  sha256: 45765a9aaf102733e76f5f60a24fa177b026e71d74f6ecddc2e9a33a6a1d7cb6

build:
  number: 5

requirements:
  build:
    - libtool  # [unix]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - libboost-python-devel
    - eigen
    - numpy
  run:
    - python

test:
  commands:
    - test -f ${PREFIX}/include/libcmaes/cmaes.h  # [unix]
    - test -f ${PREFIX}/lib/libcmaes${SHLIB_EXT}  # [unix]
  imports:
    - lcmaes

about:
  home: https://github.com/beniz/libcmaes
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: High performance blackbox stochastic optimization using the CMA-ES algorithm

extra:
  recipe-maintainers:
    - jschueller
