appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: s4yihV58IJXM57XKeoieJGYs3OwlTO/H1nwyZniRP0FbLAAsm94fwq+tegvduz4XwAEtf3i8Q/wsnixaNtQkaVQ9tRxQ5Kkv/LwNz6455r11RaS7YaWiWaSq2x7ipJ0qjtmlemEW8GPWFvUvj5mJ5WpHjk6plN8IDoFjtHDt80SgGocXnM+6auYYJq2j+/AW7N0NK1lRMEH6AEfiF+5cuiSCkXaSGWTQz0wpveaRXNBkltnLMXsOuq1mnGJFdxn6XFVaT8cpfBYJJsYpER4SeoJbeF85CD5aCvy0csKQMsSMB2LAtHA5GJQ8IEVH3s+kEojOi6Ip8oqGW6st3kCG20b8Pxp1+TQnhZfuFl0PhDBcGIWUTZZzq0eou85Lyg6Dy2k1+QdxsOwSL8pNIwxcsEDAhzT6IyDYcnf95mMKyyne7N9xdq4/LYWcQLnc/YRGCVTtwGFIMSjb5jYASxvPXP34akHgCfA3vUtCvWj+9jXvu5/x9CBkiu4pqAk6idTOwrBA+KKaYckHBbYOazRAb/ZljOyc3Sx1ageFO4/CvUzNL5IwVhKgSgRmL2V1WOfPynUvcP7WMeqiUILNyB+9kSO/P9zqUcCOq6bKXG/ahzNCWXzvWQ4O6SAhSvSvFdOIHtwiTF8gLIlCOo1GZGdM4fOvZxG1dMe/F6LnBy/hgk8=}
